### PR TITLE
Merge pull request #1 from p1v2/main

### PR DESCRIPTION
**Pull request by viktorvolchok**
HW 3

### CODE REVIEW

**Comment by viktorvolchok** [comment]
HW3

**Comment by viktorvolchok** [comment]
Applied another aggregator (Sum)

**Comment by viktorvolchok** [comment]
Applied another aggregator (Sum) HW#3

**Comment by viktorvolchok** [comment]
HW_5

**Review by p1v2 — COMMENTED** [review]
Good!

**Pull request closed without merging**
